### ISSUE TITLE
CI : Fix cannot import name 'MultiTaskDataSample'

### ISSUE THREAD

**Issue by piercus** [marouaneamz/mmclassification#12]
### Actual

PR checks of https://github.com/open-mmlab/mmclassification/pull/1229 failed
See https://github.com/open-mmlab/mmclassification/pull/1229/checks?check_run_id=9712026761

Errro says `cannot import name 'MultiTaskDataSample'`

### Expected

PR tests should work fine

**Comment by marouaneamz** [comment]
in my branch
```
python -m unittest tests/test_structures/test_datasample.py

.../home/marouane/.local/lib/python3.8/site-packages/torch/testing/_deprecated.py:35: FutureWarning: torch.testing.assert_allclose() is deprecated since 1.12 and will be removed in 1.14. Use torch.testing.assert_close() instead. For detailed upgrade instructions see https://github.com/pytorch/pytorch/issues/61844.
  warnings.warn(msg, FutureWarning)
.......
----------------------------------------------------------------------
Ran 10 tests in 0.004s

OK
```

in your branch

```
python -m unittest tests/test_structures/test_datasample.py

E
======================================================================
ERROR: test_datasample (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_datasample
Traceback (most recent call last):
  File "/home/marouane/anaconda3/envs/openmmlab1.x/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/marouane/dev/mmclassification1.x/tests/test_structures/test_datasample.py", line 8, in <module>
    from mmcls.structures import ClsDataSample, MultiTaskDataSample
ImportError: cannot import name 'MultiTaskDataSample' from 'mmcls.structures' (/home/marouane/dev/mmclassification1.x/mmcls/structures/__init__.py)


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```
I think there is an error during the merge I will try to correct it

**Comment by marouaneamz** [comment]
you forgot from .multi_task_data_sample import MultiTaskDataSample in mmcls/structures/__init__.py
